from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from langchain_core.messages import HumanMessage

from backend.app.agent.graph import build_graph
from backend.app.harness.validators import (
    validate_user_question,
    validate_final_answer
)


router = APIRouter(
    prefix="/chat",
    tags=["chat"]
)


class ChatRequest(BaseModel):
    question: str


@router.post("")
def chat(request: ChatRequest):

    if not validate_user_question(
        request.question
    ):
        raise HTTPException(
            status_code=400,
            detail="Invalid question."
        )

    graph = build_graph()

    result = graph.invoke(
        {
            "messages": [
                HumanMessage(
                    content=request.question
                )
            ],
            "tool_call_count": 0,
            "no_relevant_context": False
        }
    )

    final_message = result["messages"][-1]



    if not validate_final_answer(
        final_message.content
    ):
        raise HTTPException(
            status_code=500,
            detail="Invalid final answer generated by agent."
        )

    return {
        "question": request.question,
        "answer": final_message.content,
        "run_id": result["trace"].run_id
    }